name: kinoko futon
favicon: null
layout_spectrum: 0.0609783292748034
typography_spectrum: 0.53445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100b05'
    - '#f5f0da'
    - '#4d3a1c'
    - '#b1803d'
    - '#e0c784'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
